import CalculatorTab from '@/components/calculator-tab';
import ConvertersTab from '@/components/converters-tab';
import { Tabs, TabList, TabPanels, Tab, TabPanel } from '@chakra-ui/react';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>HELPER</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <main>
        <Tabs>
          <TabList>
            <Tab>Calculadora</Tab>
            <Tab>Conversor</Tab>
          </TabList>

          <TabPanels>
            <TabPanel>
              <CalculatorTab />
            </TabPanel>
            <TabPanel>
              <ConvertersTab />
            </TabPanel>
          </TabPanels>
        </Tabs>
      </main>
    </>
  );
}
